# Download and use an existing image which already has Conda installed and set up
FROM zeeros/tf2-env:latest
# Copy source code
# Workspace
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY train.py ./
