name: Training
inputs:
- {name: Train dataset, type: String}
outputs:
- {name: Trained model, type: String}
implementation:
  container:
    image: zeeros/tf2-env
    command: [
      python3,
      /usr/src/app/train.py,
      --input-dataset-path, {inputPath: Train dataset},
      --output-model-path, {outputPath: Trained model},
    ]
