name: Training
inputs:
- {name: Hidden layers, type: String}
- {name: Train dataset, type: String}
outputs:
- {name: Trained model, type: String}
implementation:
  container:
    image: zeeros/ddos-classifier-train
    command: [python3, /usr/src/app/train.py,
      --hidden-layers, {inputValue: Hidden layers},
      --input-dataset-path, {inputPath: Train dataset},
      --output-model-path, {outputPath: Trained model},
    ]
